-- Database: sql_controle_n2

-- DROP DATABASE sql_controle_n2;

CREATE DATABASE sql_controle_n2
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'French_France.1252'
    LC_CTYPE = 'French_France.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
	
CREATE TABLE T_CELKO_TEN_IN_ON_TIO  
(TIO_ID INTEGER NOT NULL,  
 TIO_1  INTEGER NOT NULL,  
 TIO_2  INTEGER NOT NULL,  
 TIO_3  INTEGER NOT NULL,  
 TIO_4  INTEGER NOT NULL,  
 TIO_5  INTEGER NOT NULL,  
 TIO_6  INTEGER NOT NULL,  
 TIO_7  INTEGER NOT NULL,  
 TIO_8  INTEGER NOT NULL,  
 TIO_9  INTEGER NOT NULL,  
 TIO_10 INTEGER NOT NULL); 


CREATE TABLE T_PERSONNE_PRS 
(PRS_NOM    CHAR(16) NOT NULL, 
 PRS_VILLE  CHAR(16), 
 PRS_NOMBRE INTEGER); 
 

CREATE TABLE T_AMORTISSEMENT_AMT
(AMT_FIN     CHAR(6), 
 AMT_FIN_Y2K CHAR(10)); 
				  
				  
CREATE TABLE T_CHAMBRE_CHB
(CHB_NUM INTEGER); 

CREATE TABLE T_PLANNING_PLN 
(PLN_JOUR  DATE, 
 CHB_NUM   INTEGER, 
 PLN_LIBRE CHAR(5)); 
				
				
CREATE TABLE T_CLIENT_CLI
(CLI_ID             INTEGER,
 CLI_NOM            VARCHAR(16),
 CLI_DATE_NAISSANCE DATE); 
				
CREATE TABLE T_ENTIER_ENT 
(ENT_N INTEGER); 
				
CREATE TABLE T_NUMERO_NMR 
(NMR INTEGER); 	
				
CREATE TABLE T_FACTURE_FAC 
(FAC_NUM  INTEGER, 
 FAC_DATE DATE); 

CREATE TABLE T_LIGNE_FACTURE_LIF 
(LIF_NUM     INTEGER, 
 FAC_NUM     INTEGER, 
 LIF_ARTICLE VARCHAR(16), 
 LIF_MONTANT DECIMAL(16,2)); 
					 
					 
CREATE TABLE T_TRADUCTION_TDR 
(TDR_ID      INTEGER, 
 TDR_LANGUE  VARCHAR(8),
 TDR_LIBELLE VARCHAR(256)); 
					 
CREATE TABLE T_PANEL_PNL
(PNL_NOM VARCHAR(16),
 PNL_REPONSE1 INTEGER,
 PNL_REPONSE2 INTEGER,
 PNL_REPONSE3 INTEGER,
 PNL_REPONSE4 INTEGER,
 PNL_REPONSE5 INTEGER); 

CREATE TABLE T_REPONSES_RPS
(RPS_REPONSE1 INTEGER, 
 RPS_REPONSE2 INTEGER, 
 RPS_REPONSE3 INTEGER, 
 RPS_REPONSE4 INTEGER, 
 RPS_REPONSE5 INTEGER); 
					 
					 

				
				